
/// Returns a list of your products. The products are returned sorted by creation date, with the most recently created products appearing first.
public struct GetProducts: StripeAPIEndpoint {
	public typealias inputType = AnyCodable
	public typealias outputType = ProductList
	public typealias paramType = Params
	
	public struct Params {
		let active: Bool?
		let ending_before: String?
		let limit: Int?
		let shippable: Bool?
		let starting_after: String?
		let url: String?

		/// Initialize the request parameters
		/// - Parameter active: Only return products that are active or inactive (e.g., pass `false` to list all inactive products).
		/// - Parameter ending_before: A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.
		/// - Parameter limit: A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
		/// - Parameter shippable: Only return products that can be shipped (i.e., physical, not digital products).
		/// - Parameter starting_after: A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.
		/// - Parameter url: Only return products with the given url.
		public init(active: Bool? = nil, ending_before: String? = nil, limit: Int? = nil, shippable: Bool? = nil, starting_after: String? = nil, url: String? = nil) {
			self.active = active
			self.ending_before = ending_before
			self.limit = limit
			self.shippable = shippable
			self.starting_after = starting_after
			self.url = url
		}
	}
	public static func endpoint(for inputs: Params) throws -> String {
		var params = [String]()
		if let a = inputs.active?.urlEncoded { params.append("active=\(a)") }
		if let a = inputs.ending_before?.urlEncoded { params.append("ending_before=\(a)") }
		if let a = inputs.limit?.urlEncoded { params.append("limit=\(a)") }
		if let a = inputs.shippable?.urlEncoded { params.append("shippable=\(a)") }
		if let a = inputs.starting_after?.urlEncoded { params.append("starting_after=\(a)") }
		if let a = inputs.url?.urlEncoded { params.append("url=\(a)") }
		let query = params.joined(separator: "&")
		return "/v1/products?\(query)"
	}
	public static var method: HTTPMethod { return .GET }

	public final class ProductList: Codable {
		/// Details about each object.
		public var data: [Product]
		/// True if this list has another page of items after this one that can be fetched.
		public var has_more: Bool
		/// String representing the object's type. Objects of the same type share the same value. Always has the value `list`.
		public var object: ObjectValues
		/// The URL where this list can be accessed.
		public var url: String

		public init(data: [Product], has_more: Bool, object: ObjectValues, url: String) {
			self.data = data
			self.has_more = has_more
			self.object = object
			self.url = url
		}

		public enum ObjectValues: String, Codable {
			case list = "list"
		}
	}

}

/// Creates a new product object.
public struct PostProducts: StripeAPIEndpoint {
	public typealias inputType = FormInput
	public typealias outputType = Product
	public typealias paramType = AnyCodable
	public static func endpoint(for inputs: AnyCodable) throws -> String {
		return "/v1/products"
	}

	public final class FormInput: Codable {
		/// Whether the product is currently available for purchase. Defaults to `true`.
		public var active: Bool?
		/// The product's description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
		public var description: String?
		/// Specifies which fields in the response should be expanded.
		public var expand: [String]?
		/// An identifier will be randomly generated by Stripe. You can optionally override this ID, but the ID must be unique across all products in your Stripe account.
		public var id: String?
		/// A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
		public var images: [String]?
		/// Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
		public var metadata: AnyCodable?
		/// The product's name, meant to be displayable to the customer. Whenever this product is sold via a subscription, name will show up on associated invoice line item descriptions.
		public var name: String
		/// The dimensions of this product for shipping purposes.
		public var package_dimensions: PackageDimensionsSpecs?
		/// Whether this product is shipped (i.e., physical goods).
		public var shippable: Bool?
		/// An arbitrary string to be displayed on your customer's credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all.  This may be up to 22 characters. The statement description may not include `<`, `>`, `\`, `"`, `'` characters, and will appear on your customer's statement in capital letters. Non-ASCII characters are automatically stripped.  It must contain at least one letter.
		public var statement_descriptor: String?
		/// A [tax code](https://stripe.com/docs/tax/tax-codes) ID.
		public var tax_code: String?
		/// A label that represents units of this product in Stripe and on customers’ receipts and invoices. When set, this will be included in associated invoice line item descriptions.
		public var unit_label: String?
		/// A URL of a publicly-accessible webpage for this product.
		public var url: String?

		public init(name: String, active: Bool? = nil, description: String? = nil, expand: [String]? = nil, id: String? = nil, images: [String]? = nil, metadata: AnyCodable? = nil, package_dimensions: PackageDimensionsSpecs? = nil, shippable: Bool? = nil, statement_descriptor: String? = nil, tax_code: String? = nil, unit_label: String? = nil, url: String? = nil) {
			self.name = name
			self.active = active
			self.description = description
			self.expand = expand
			self.id = id
			self.images = images
			self.metadata = metadata
			self.package_dimensions = package_dimensions
			self.shippable = shippable
			self.statement_descriptor = statement_descriptor
			self.tax_code = tax_code
			self.unit_label = unit_label
			self.url = url
		}


		/// The dimensions of this product for shipping purposes.
		public final class PackageDimensionsSpecs: Codable {
			public var height: StringNumber
			public var length: StringNumber
			public var weight: StringNumber
			public var width: StringNumber

			/// The dimensions of this product for shipping purposes.
			/// - Parameters:
			///   - height: 
			///   - length: 
			///   - weight: 
			///   - width: 
			public init(height: StringNumber, length: StringNumber, weight: StringNumber, width: StringNumber) {
				self.height = height
				self.length = length
				self.weight = weight
				self.width = width
			}
		}

	}

}

/// Retrieves the details of an existing product. Supply the unique product ID from either a product creation request or the product list, and Stripe will return the corresponding product information.
public struct GetProductsId: StripeAPIEndpoint {
	public typealias inputType = AnyCodable
	public typealias outputType = Product
	public typealias paramType = Params
	
	public struct Params {
		let id: String

		/// Initialize the request parameters
		/// - Parameter id: 
		public init(id: String) {
			self.id = id
		}
	}
	public static func endpoint(for inputs: Params) throws -> String {
		return "/v1/products/\(inputs.id)"
	}
	public static var method: HTTPMethod { return .GET }

}

/// Updates the specific product by setting the values of the parameters passed. Any parameters not provided will be left unchanged.
public struct PostProductsId: StripeAPIEndpoint {
	public typealias inputType = FormInput
	public typealias outputType = Product
	public typealias paramType = Params
	
	public struct Params {
		let id: String

		/// Initialize the request parameters
		/// - Parameter id: 
		public init(id: String) {
			self.id = id
		}
	}
	public static func endpoint(for inputs: Params) throws -> String {
		return "/v1/products/\(inputs.id)"
	}

	public final class FormInput: Codable {
		/// Whether the product is available for purchase.
		public var active: Bool?
		/// The product's description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
		public var description: String?
		/// Specifies which fields in the response should be expanded.
		public var expand: [String]?
		/// A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
		public var images: AnyCodable?
		/// Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
		public var metadata: AnyCodable?
		/// The product's name, meant to be displayable to the customer. Whenever this product is sold via a subscription, name will show up on associated invoice line item descriptions.
		public var name: String?
		/// The dimensions of this product for shipping purposes.
		public var package_dimensions: AnyCodable?
		/// Whether this product is shipped (i.e., physical goods).
		public var shippable: Bool?
		/// An arbitrary string to be displayed on your customer's credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all.  This may be up to 22 characters. The statement description may not include `<`, `>`, `\`, `"`, `'` characters, and will appear on your customer's statement in capital letters. Non-ASCII characters are automatically stripped.  It must contain at least one letter. May only be set if `type=service`.
		public var statement_descriptor: String?
		/// A [tax code](https://stripe.com/docs/tax/tax-codes) ID.
		public var tax_code: String?
		/// A label that represents units of this product in Stripe and on customers’ receipts and invoices. When set, this will be included in associated invoice line item descriptions. May only be set if `type=service`.
		public var unit_label: String?
		/// A URL of a publicly-accessible webpage for this product.
		public var url: String?

		public init(active: Bool? = nil, description: String? = nil, expand: [String]? = nil, images: AnyCodable? = nil, metadata: AnyCodable? = nil, name: String? = nil, package_dimensions: AnyCodable? = nil, shippable: Bool? = nil, statement_descriptor: String? = nil, tax_code: String? = nil, unit_label: String? = nil, url: String? = nil) {
			self.active = active
			self.description = description
			self.expand = expand
			self.images = images
			self.metadata = metadata
			self.name = name
			self.package_dimensions = package_dimensions
			self.shippable = shippable
			self.statement_descriptor = statement_descriptor
			self.tax_code = tax_code
			self.unit_label = unit_label
			self.url = url
		}
	}

}

/// Delete a product. Deleting a product is only possible if it has no prices associated with it. Additionally, deleting a product with <code>type=good</code> is only possible if it has no SKUs associated with it.
public struct DeleteProductsId: StripeAPIEndpoint {
	public typealias inputType = AnyCodable
	public typealias outputType = DeletedProduct
	public typealias paramType = Params
	
	public struct Params {
		let id: String

		/// Initialize the request parameters
		/// - Parameter id: 
		public init(id: String) {
			self.id = id
		}
	}
	public static func endpoint(for inputs: Params) throws -> String {
		return "/v1/products/\(inputs.id)"
	}
	public static var method: HTTPMethod { return .DELETE }

}
